# 3 - Lists, Arrays, and NumPy<br>*(Ch. 2.4)*

## Lists

### Lists are the basic *container* in Python.

* A list is framed with brackets, and items are separated by commas.

* The items in a list don't need to be of the same type (though practically speaking they often are).

Examples:

```python
x1 = [1,2,3]
x2 = ['a string',2,3.5,['a list in a list','how silly']]
```

If you wish to access a single element from a list (for instance, in a calculation), they can be accessed using `r[0]`, `r[1]`, ... , `r[n-1]` if there are *n* elements in list `r`.

Try the following:
```python
from math import sqrt
r = [1.0, 1.5, -2.2]
length = sqrt( r[0]**2 + r[1]**2 + r[2]**2)
print(length)
```

<br><br><br><br><br><br><br><br>
Note: In a lot of ways, `strings` can **almost** be thought of as lists of characters in that indexing and other manipulations that we discuss for lists will also work on strings. As an example, if `x = 'This class is great!'` then `x[0]` will return `T` and `x[7]` will return `a`.

In [ ]:
x = 'This class is great!'
print(x[0])

<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

### Lists are *mutable*, meaning items can be reassigned after creation.

Example:

```python
x = [1,2,3]
x[0] = 5
print(x)
```

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

### Be careful: integers are still immutable.

Example:


In [1]:
a = 1
x = [a,2,3]
a = 3
print(x)

[1, 2, 3]


<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

### Operations can be performed on entire lists at once
A few example functions that can be used on lists include:

* sum(list)    Calculates the sum of elements in the list

* max(list)    Finds the maximum value contained in the list

* min(list)    Finds the minimum value contained in the list

* len(list)    Determines the number of elements in the list

Example:
```python
r = [ 1.0, 1.5, -2.2 ]
mean = sum(r)/len(r)
print(mean)
```
<br><br><br><br>
### The `map` function allows mathematical operations to be conducted on each individual list element

For example, the following code finds the square root of each list element:
```python
from math import sqrt
r = [ 1.0, 1.5, 2.2 ]
root_r = list(map(sqrt,r))
print(root_r)
```

In [ ]:
from math import sqrt
r = [ 1.0, 1.5, 2.2 ]
root_r = list(map(sqrt,r))
print(root_r)

<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

### Lists (and strings) have *methods*

See official documentation for a more complete list (and for a list of methods associated with string variables). A few common examples for methods **associated with lists** include:

* `append(element)    to add an element to the end of a list`

* `extend(list)       to add a second list to the first`

* `index(element)     Return the lowest index of the list containing *element*`

* `insert(index, element)  Insert *element* at index *index*`

* `sort()             to reorder the items in a list in ascending order`

* `reverse()          reverses the order of the list`

* `pop()              removes the last item in the list and returns that item as the result. Alternatively, pop(<i>) removes the item at index i`

* `copy()             Return a copy of the list.`

* `count(element)     Return the number of elements equal to *element* in the list.`

For instance, try the following:


In [ ]:
x = [1,2,3]
print(x)

x.reverse()
print(x)

x.append(4)
print(x)

y = x.pop()
print(y,x)

y = x.copy()
print(x,y)

a = "What's going on here?"
a.pop()
print(a)

<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
## Creating and modifying a NumPy array

A Numpy *array* is very similar to a list, with the following key differences:

1. The elements in an array must all be of the same type. 

2. Arrays can have more than one dimension. (A one-dimensional array behaves like a *vector*; a two-dimensional array behaves like a *matrix*.)

3. Mathematical operations on arrays are generally much faster than on lists.

Try the following code, which demonstrates the basic methods for generating arrays:

In [ ]:
import numpy as np

# Create a 1D array of 4 zeros (floating point):
a1 = np.zeros(4,float)

# Create a 2D array of zeros with 3 rows, 4 columns:
a2 = np.zeros([3,4],float)

# As above, but with ones instead of zeros:
a3 = np.ones([3,4],float)

# Create an empty array 
#(faster, but with junk entries that you should overwrite before use)
a6 = np.empty([5,5],float)

# Create an array with a list or list of lists
r = [[1.0,2,3],[5.5,4.4,9]]
a5 = np.array(r,float)

#print(a1)
#print(a2)
#print(a3)
print(a5)
#print(a5)

a7 = np.array([[1,2.2,3+4j],[5.4,7,9]])

print(a7)

<br><br><br><br><br><br><br><br><br><br><br><br>

### We can also save and load arrays directly from a .txt file.

We do this with `np.savetxt()` and `np.loadtxt()`:

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]],float)
np.savetxt('demo_array.txt',a)

b = np.loadtxt('demo_array.txt')
print(b)

<br><br><br><br><br><br><br><br><br><br><br><br>

### Arrays can be indexed with notation similar to lists.

For a 1D array, the syntax is *identical* to lists:

In [2]:
import numpy as np
a = np.array([1,2,3],float)
a[0] = 5.5
print(a)

[5.5 2.  3. ]


<br><br><br><br><br><br><br><br><br><br>

For an array with >1 dimension, indices are separated by commas within a bracket:

In [8]:
a = np.empty([2,4],int)
a[0,1] = 1
a[1,0] = -1
print(a)

[[743415920       520         0         0]
 [      952         0       768     32767]]


<br><br><br><br><br><br><br><br><br><br>

Finally, you can append new rows to an array with the `np.vstack((<array>,<new row>))` command:

In [12]:
a = np.array([[1,2,3],[4,5,6]],float)
b = np.array([7,8,9],float)

a = np.vstack((a,b))
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


<br><br>

There are *many* commands for splitting, rotating, reshaping, and otherwise modifying the structure of arrays. We won't mess with them (though you might want to for your project!).

<br><br><br><br><br><br><br><br><br><br>
## Slicing strings, lists, and arrays
Sometimes you only want to use/reassign a portion of a string, list, or array. The syntax for slicing is:

* `s[i]` returns the character at the specified index.

    + The first character is at index 0, and the last is at index N-1 (for N characters)
    
    + You can count backwards with a negative index, so `s[-1]` returns the final character, `s[-2]` the second-to-last character, etc.
    
* `s[i:j]` returns a range of characters starting at i and stopping before j.

    + This guarantees that the length of what is returned is j-i (e.g. `s[3:5]` returns 2 characters).
    
    + Omiting i defaults to 0 (e.g. `s[:2]` is the same as `s[0:2]`).
    
    + Omiting j defaults to "end of string" (e.g. `s[1:]` is the entire string except for the first character).
    
    + Be aware that you can't directly slice across the 0 index (e.g. `s[-1:1]` returns an empty string).
    
* `s[i:j:k]` is the same as the above, but with a *stride* k such that every kth character is returned. 

    + If k is negative, the stride is in reverse order (so `s[::-1]` reverses a string).
    

* `s[i:j,m:n]` returns a range of elements from a two-dimensional array `s` starting at i and stopping before j in the 1st dimension and starting from m and ending before n in the second dimension.

    + If the array has more than two dimensions, just tack on additional arguments after a comma. (e.g. `s[i:j, m:n, p:q, r:s]` for a four-dimensional array).

With all of this in mind, try the following example.

<br><br><br><br><br><br><br><br>

### Example

Write a program with the first line:

```python
s = "I'm a little teapot"
```

Then use object *s* to generate the following strings:

+ s1 = "I'm a little"

+ s2 = "potI'm a"

+ s3 = "teapot", in reverse order



In [23]:
s = "I'm a little teapot"
s2 = s[-3:] + s[0:5]
print(s2)

potI'm a


In [ ]:
s = "I'm a little teapot"
print(s[:12])
print(s[-3:]+s[0:5])
print(s[:-7:-1])

<br><br><br><br><br><br><br><br><br><br><br><br><br>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
Try slicing array `r` as follows:


In [24]:
import numpy as np
r = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],int)
print(r)
print()
print(r[1,1:3])
print()
print(r[1,:])
print()
print(r[:,3])
print()
print(r[1:3,2:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[7 8]

[ 6  7  8  9 10]

[ 4  9 14]

[[ 8  9 10]
 [13 14 15]]


<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

## Arithmetic with Arrays

### Standard mathematical operators are applied *element-wise*. Try the following:

In [27]:
a1 = np.array([1,2,3],float)
a2 = np.array([4,5,6],float)

print(a1 + a2)
print(a2 - a1)
print(a1*2)
print(a1/4)


[5. 7. 9.]
[3. 3. 3.]
[2. 4. 6.]
[0.25 0.5  0.75]


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

## Numpy can perform vector algebra

### Consider the dot product between two vectors:

$$ \Large \vec{u} = u_{x}\hat{x} + u_{y}\hat{y} + u_{z}\hat{z}$$
$$ \Large \vec{v} = v_{x}\hat{x} + v_{y}\hat{y} + v_{z}\hat{z}$$

$$ \Large \vec{u} \cdot \vec{v} = uvcos(\theta) = u_{x}v_{x} + u_{y}v_{y} + u_{z}v_{z}$$

In words, the dot product is a scalar with magnitude given by the product of the *parallel components* of the vectors. In physics, this is often what is meant by default when referring to the product of two vectors. 

In Numpy, we use the `np.dot(a,b)` command:

In [2]:
import numpy as np
a = np.array([1,2,3],float)
b = np.array([4,5,6],float)
print(np.dot(a,b))

32.0


Confirm the output of the above code by calculating $\vec{u}\cdot\vec{v}$ by hand.
<br><br><br><br><br><br><br><br><br><br><br><br>

### The cross product of two vectors is handled in a similar way:

$$ \Large \vec{u} = u_{x}\hat{x} + u_{y}\hat{y} + u_{z}\hat{z}$$
$$ \Large \vec{v} = v_{x}\hat{x} + v_{y}\hat{y} + v_{z}\hat{z}$$

$$ \Large \vec{u} \times \vec{v} = uvsin(\theta)\hat{n} = \begin{vmatrix} \hat{x} & \hat{y} & \hat{z} \\ u_x & u_y & u_z \\ v_x & v_y & v_z \end{vmatrix} = (u_y v_z-u_z v_y)\hat{x} + (u_z v_x - u_x v_z)\hat{y} + (u_x v_y-u_y v_x)\hat{z}$$

where $\hat{n}$ is a direction perpendicular to both $\vec{u}$ and $\vec{v}$ in a direction given by the right hand rule. In words, the cross product is a vector perpendicular to both $u$ and $v$ that measures the extent to which $u$ and $v$ are perpendicular. A simple example from physics is *torque*: a door swings most easily when you push perpendicular to the door.

In Numpy, we use the `np.cross(a,b)` command:


In [3]:
a = np.array([1,2,3],float)
b = np.array([4,5,6],float)
print(np.cross(a,b))

[-3.  6. -3.]


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

## Numpy can perform matrix algebra

(This is the realm of *linear algebra*)

We won't worry about this too much, as there is no expectation that you have studied linear algebra. However, let's describe a few simple examples for those of you who have or will study these topics.

### Matrices can be multiplied with `np.dot(a,b)`:

$$ \Large         \begin{pmatrix}1 & 2 \\0 & 1 \end{pmatrix} \begin{pmatrix}1 & 2 \\3 & 4 \end{pmatrix} = \begin{pmatrix}7 & 10 \\3 & 4 \end{pmatrix}$$


In [6]:
a = np.array([[1,2],[0,1]],float)
b = np.array([[1,2],[3,4]],float)
print(np.dot(a,b))


[[ 7. 10.]
 [ 3.  4.]]


<br><br><br><br><br><br><br><br>

### The determinant of a matrix can be computed with `np.linalg.det(a)`:

In [8]:
a1 = np.array([[1,2],[3,4]],float)
# This is just 1*4-2*3 = -2
print(a1)
print(np.linalg.det(a1))

a2 = np.array([[5,8,10,16],
               [-6,-4,3,10],
              [0.25,4.2,3.9,0],
              [4,5,6,7.5]])
# This would take a long time to compute by hand!
print(a2)
print(np.linalg.det(a2))

[[1. 2.]
 [3. 4.]]
-2.0000000000000004
[[ 5.    8.   10.   16.  ]
 [-6.   -4.    3.   10.  ]
 [ 0.25  4.2   3.9   0.  ]
 [ 4.    5.    6.    7.5 ]]
630.4999999999997


<br><br><br><br><br><br><br><br>

### The eigenvalues $ \lambda$ and eigenvectors $\vec{v}$ of a matrix $\bf{A}$ satisfy the equation $ \bf{A}\cdot \vec{v}=\lambda \vec{v}$ and can be computed with `np.linalg.eig(a)`:

In [9]:
# Using a2 from above
vals, vects  = np.linalg.eig(a2)
print(vals)
print('\n',vects)

[-5.89516118 -1.41892129  5.18953585 14.52454663]

 [[-0.12177349  0.37112427 -0.74166923  0.86325766]
 [ 0.90560355 -0.72963281  0.19493493 -0.00430187]
 [-0.38519954  0.55869914  0.49111421  0.01861223]
 [-0.1291307  -0.13325915 -0.41319965  0.50440191]]


<br><br><br><br><br><br><br><br>
### Applying the built-in Python functions `sum`, `max`, `min`, `len`, and others to arrays can result in erratic behavior.

Use similar *methods* from the `numpy` package, as seen in the following examples:

In [10]:
a = np.array([[1,2,3],[4,5,6]],int)
sz = a.size # sz = np.size(a)
nrow = a.shape[0]
ncol = a.shape[1]
print('There are',sz,'elements.')
print('There are',nrow,'rows.')
print('There are',ncol,'columns.')

There are 6 elements.
There are 2 rows.
There are 3 columns.


Further array methods in the `numpy` package can be found at www.scipy.org

<br><br><br><br><br><br><br><br>
### Some functions in `numpy` have the same name as functions in `math`. 

Both `numpy` and `math` have functions named `log`. Use numpy functions to operate on numpy arrays. This highlights the reason why we use calls of the following form at the beginning of programs:
```python
import numpy as np
import math
```
Now, we can specify which version of the `log` function we want to use by typing either `np.log()` or `math.log()`. Alternatively, you can import just a single version of the function like so:
```python
from numpy import log
from math import exp
```
Now, when you use `log()` (without the `np.` prefix), you will use the version from `numpy` and when you use `exp()`, you will be using the `math` version.

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

Predict the output of the following commands. Then, try it!


In [11]:
from numpy import array
a = array([1,1],int)
b = a
print(a)
print(b)
a[0] = 2
print(a)
print(b)

[1 1]
[1 1]
[2 1]
[2 1]


<br><br><br><br>
### Warning: Be careful when copying arrays (or lists)!

The command `b = a` when using arrays **does not** create a new array `b`. Instead, it declares 'b' to be a new name for 'a' so that 'a' and 'b' both refer to the same locations in the computer memory.

Instead, try the following:


In [12]:
%reset
#from numpy import array, copy
import numpy as np
a = np.array([1,1],int)
b = np.copy(a)
print(a)
print(b)
a[0] = 2
print(a)
print(b)

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


[1 1]
[1 1]
[2 1]
[1 1]
